language: python
branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

install:
    - pip install -U pip tox codecov

env:
  - KAFKA_BROKER=localhost:9092 ZOOKEEPER=localhost:2181

script:
    - ./kafka-install.sh
    - tox

after_success:
    - codecov